# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 551a4361fbcdfe61964f5169073672a8fdf82ea5f35d978addd86bcb2236b22adc1ea9646058f11885960a519e5cf35e2dca5798dfa13e0ec505877c047dc7cb

test:
  secret_key_base: d6493e47b82ef2bd38b36d5a8eddfc8099a9a5effa792b64faf6aeeccb17da3b66cf9b3c40c62bb361049f8651713a4a1797af9399c61dfb7af3883c36b07649

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
